# Generated by Django 6.0.7 on 2026-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookissue_fine_amount_bookissue_issued_by_bookfine'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
