# Generated by Django 6.0.7 on 2026-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faculty_courses_faculty_mentors_faculty_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
